### ISSUE TITLE
socket time out

### ISSUE THREAD

**Issue by 2991535823** [czasg/pywss#213]
作者你好，我是一名才接触前端的用户，我使用pywss ，会遇见sokect time out问题,html 能正常访问 ，自己定义 api也能访问，访问后过一段时间报 sokect time out，结构如下只是在```GET/js/app.3ebcdc31.js```不同，我使用demo/chat，就遇不见这个问题，我的index.html是使用的vue开发后打包的。 请问这是什么原因，该怎么解决呀？
```
time="2024-04-19 15:27:23.836300" level=error msg=traceback route="GET/js/app.3ebcdc31.js" error="Traceback (most recent call last):
  File "/home/bera/Conda_env/pgui/lib/python3.8/site-packages/pywss/__init__.py", line 640, in handler_request
    http_method, http_url, http_version, err = parse_request_line(rfd)
  File "/home/bera/Conda_env/pgui/lib/python3.8/site-packages/pywss/headers.py", line 36, in parse_request_line
    line = fp.readline(65537)
  File "/home/bera/Conda_env/pgui/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out"
time="2024-04-19 14:45:52.855284" level=error msg=traceback route="GET/test" error="Traceback (most recent call last):
  File "/home/bera/Conda_env/pgui/lib/python3.8/site-packages/pywss/__init__.py", line 640, in handler_request
    http_method, http_url, http_version, err = parse_request_line(rfd)
  File "/home/bera/Conda_env/pgui/lib/python3.8/site-packages/pywss/headers.py", line 36, in parse_request_line
    line = fp.readline(65537)
  File "/home/bera/Conda_env/pgui/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out"
```

我的文件目录结构是
```
-static
  -js
     chunk-vendors.7ad5b465.js
     app.3ebcdc31.js
  -img
     favicon.ico
  -css
     app.1facf82d.css
  index.html
main.py
```
main.py 文件内容如下
```python
import pywss
import sys
import signal
import rospy
from threading import Thread
sys.path.append('./api/')
#这是自己写的ros 的api，应该没有影响
from api import RVPublisher,RVSubscriber
from std_msgs.msg import String,Int64
import rospy
app = pywss.App()
msg=RVSubscriber(String,"/sendtopic")
pub=RVPublisher(Int64,'/setint',1)


def websocket(ctx: pywss.Context):
    # 升级 WebSocket
    err = pywss.WebSocketUpgrade(ctx)
    if err:
        ctx.log.error(err)
        ctx.set_status_code(pywss.StatusBadRequest)
        return
    # 轮询获取消息，实际使用场景建议引入心跳/探活机制
    try:
        while True:
            data = ctx.ws_read()
            print(data)
            ctx.ws_write(b"hello")
    except Exception as e:
        print(e)
        raise e
    
def test(ctx:pywss.Context):
    ctx.write(msg.getmsg(refresh=True))

def server():

    app.static("", rootDir="./static")
    app.get("/wechat", websocket)
    app.get("/test",test)
    app.get("/", lambda ctx: ctx.redirect("/index.html"))

    app.run(host='0.0.0.0',port=8080)

#每次ctrl+c关闭程序，重新启动报错，sock.bind(addr) OSError: [Errno 98] Address already in use，尝试app.close无效
def signal_handler(signal, frame):
    app.close()
    rospy.signal_shutdown("Ctrl C")

signal.signal(signal.SIGINT,signal_handler)
if __name__ == '__main__':
    Thread(target=lambda: rospy.init_node('flask_listener', disable_signals=True)).start()
    server()
    
```

index .html 文件内容如下
```html
<!doctype html>
<html lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="/favicon.ico">
    <title>fronted</title>
    <script defer="defer" src="/js/chunk-vendors.7ad5b465.js"></script>
    <script defer="defer" src="/js/app.3ebcdc31.js"></script>
    <link href="/css/app.1facf82d.css" rel="stylesheet">
</head>

<body><noscript><strong>We're sorry but fronted doesn't work properly without JavaScript enabled. Please enable it to
            continue.</strong></noscript>
    <div id="app"></div>
</body>

</html>
```

**Comment by czasg** [comment]
感谢你的反馈，我本地已经成功复现了。

首先，**这个问题应该不影响你的业务功能。**

这里 `socket.timeout: timed out` 报错，是因为底层tcp连接长时间没有数据交互，导致超时抛出异常。

一般系统默认tcp超时时间是小时级别的。
因此正常情况下不太好复现，这可能是你在 demo/chat 中无法复现的原因。
我通过 `socket.setdefaulttimeout(20)` 调整最大超时时间后可以复现。

在浏览器和后端交互场景下，一般会维持一个至多个tcp长连接。
因此理论长时间没有数据交互的场景下会发生这种异常。

**建议你暂时忽略这个错误。**
我计划在下一个版本迭代以下内容：
- 捕获`socket.timeout`异常
- 优化日志输出

**Comment by 2991535823** [comment]
谢谢大佬的解答，我这边这个报错一般是感觉不到10分钟，我没有去认真测时间，另外就是使用Ctrl c关闭服务器，然后立马重新启动是不行的，使用flask并不会出现这种情况，每次要等一会才能重新启动，自己研究半天也看不懂，希望后面能够得到解决，谢谢大佬😊

**Comment by czasg** [comment]
> 每次要等一会才能重新启动

这个预计是多久呢。立马重新启动是会抛出异常还是卡主？

如果抛出异常，可以提供一些日志。

如果卡主，我感觉可能是你的多线程使用姿势不对。
可以试试改下多线程的启动方式，加上 `daemon=True`：
```
Thread(target=lambda: rospy.init_node('flask_listener', disable_signals=True), daemon=True).start()
```

**Comment by 2991535823** [comment]
主要日志是sock.bind(addr) OSError: [Errno 98] Address already in use

**Comment by czasg** [comment]
这个错误是端口被占用了。

一般发生这种情况是因为你上一个服务还没有完全退出，新服务又启动了，导致端口冲突了。

我本地暂时没法复现。

你使用的版本是那个版本呢？启动服务时应该会输出当前版本号。
```
time="2024-04-19 18:15:02.255634" level=info msg="server start" version="0.1.27" host="0.0.0.0" port=8080
```

**Comment by 2991535823** [comment]
出现这种报错，主要是启动服务器，网页建立访问后会这样，可以在Demo/chat复现，版本0.1.27，Python app.py后，浏览器访问界面，Ctrl C关闭服务器，重新启动就sock.bind((host，port)) OSError: [Errno 98] Address already in use

**Comment by czasg** [comment]
> Python app.py后，浏览器访问界面，Ctrl C关闭服务器，重新启动就sock.bind((host，port)) OSError: [Errno 98] Address already in use

我本地使无法复现。

你那边关闭服务器后，是否会输出`server closed`日志，比如：
```
time="2024-04-20 20:46:20.417195" level=warning msg="server closed"
```
如果正常输出了，那端口资源应该是正常释放了的。

**Comment by 2991535823** [comment]
会输出server close，虽然不影响使用，谢谢大佬了
